version: '3'
services:

  #PHP Service
  expensee-app:
    build: .
    container_name: expensee-app
    restart: unless-stopped
    tty: true
    env_file:
      - .env
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - .:/app